language: objective-c
rvm: 1.9.3
before_install:
  - gem install cocoapods
script:
  - xctool test -workspace fieldworksdiary.xcworkspace -scheme fieldworksdiaryTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
